# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Compose samples CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'manual build trigger'
      home:
        description: 'location'
        required: false

jobs:
  build-test-and-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: clean
      run: |
        ./gradlew clean --info

    - name: assemble debug
      run: |
        ./gradlew assembleDebug --info

    - name: unit tests
      run: |
        ./gradlew testDebugUnitTest --info

    - name: lint
      run: |
        ./gradlew lintDebug --info

    - name: ktlint
      run: |
        ./gradlew ktlint --info
